// Interface for the config object
export interface Config {
  AppName: string;
  ContactEmailsFlag: boolean;
  ContactEmails: string[];
  ZoomFactor: number;
  ServerBackEndUrl: string;
  ServerLocation: string;
  ServerUrl: string;
  postFixServerToken: boolean;
  bearerToken: string;
  debugMode: boolean;
  setCADViewerLanguage: string;
  initFileName: string;
  canvasMode: string;
  UploadNewFile: string;
  activateCompareOnLoad: boolean;
  cadviewerLicenseKey: string;
  conversionParameters: { param: string; value: string }[];
  defaultLayerColorsOnLoad: { layer: string; color: string }[];
  defaultLayerSetTimeout: number;
  currentView: string[];
  ShowInformativeBottomPanel: boolean;
  ShowInformativeBottomPanelWhenClickInLeftPanel: boolean;
  ShowInformativeLeftPanel: boolean;
  bottomPaneSliderMode: string;
  bottomPaneDefaultHeight: number;
  rightPanelDefaultWidth: number;
  leftPaneDefaultWidth: number;
  setCallbackMeasurement: boolean; // set the callback measurement function
  printPDFflag: boolean;
  printAsPDF: boolean;
  setPaperSize: string;
  printMargins_nonprint_h: number;
  printMargins_nonprint_w: number;
  printMargins_standard_h: number;
  printMargins_standard_w: number;
  printMargins_tiny_h: number;
  printMargins_tiny_w: number;
  printMargins_none_h: number;
  printMargins_none_w: number;
  DisplayCoordinatesMenu: boolean;
  displayTopNavigationBar: boolean;
  setSpaceObjectsCustomMenu: boolean;
  hideLeftHamburgerMenu: boolean;
  floatingToolbar: boolean;
  floatingToolbarOrientation: string;
  floatingToolbarIconSize: string;
  displayTopMenuIconBar: boolean;
  setTopMenuXMLDirect: boolean;
  topMenuXML: string;
  topMenuXMLpath: string;
  setZoomImageWallpaper: boolean;
  setZoomImageWallpaper_scalefactor: number;
  setZoomImageWallpaper_scalebreakpoint: number;
  setScrollWheelThrottleDelay: number;
  setScrollWheelZoomSteps: number;
  setScrollWheelDefaultZoomFactor: number;
  setNormalizeFixedLineWeights: boolean;
  setNormalizeFixedLineWeightsFactor: number;
  setBPLayerChange: boolean;
  BaseAttributes: {
    fill: string;
    "fill-opacity": number | string;
    stroke: string;
    "stroke-width": number | string;
    "stroke-linejoin": string;
    "stroke-opacity": number | string;
  };
  HighlightAttributes: {
    fill: string;
    "fill-opacity": number | string;
    stroke: string;
    "stroke-width": number | string;
    "stroke-linejoin"?: string;
    "stroke-opacity"?: number | string;
  };
  SelectAttributes: {
    fill: string;
    "fill-opacity": number | string;
    stroke: string;
    "stroke-width": number | string;
    "stroke-linejoin"?: string;
    "stroke-opacity"?: number | string;
  };
  defaultSpaceObjectColor :{
    fill: string;
    "fill-opacity": number | string;
    stroke: string;
    "stroke-width": number | string;
    "stroke-linejoin"?: string;
    "stroke-opacity"?: number | string;
  };
  controlPointsStyleObject :{
        fill: string;
        stroke: string;
        opacity: number | string;
        radiusFactor: number | string;
  };

  topMenuXML_config_file: string;
  setUnitForCalibrate: string;
  adjustMinimumLineThickness: number;
  setNoModalMode: boolean;
  setSpaceNameAsTypeInPopup: boolean;

  enableDemoNavigation: boolean;
  CADViewerPublicDemo: boolean;
  setRedlineModeInfo: boolean;
  setRedlineDynamicPath: boolean;
  setSpaceObjectDynamicPath: boolean;
  setImageObjectDynamicPath: boolean;
  setCADViewerSkin: string;
  rightMenuMode: string;
  rightMenuPopupText: string;
  enableRightMenuIcon: boolean;
  enableRightFileModalPanel: boolean;
  enableRightFileModalPanelText: string;
  rightFileModalPanelTitle: string;
  rightFileModalPanelSubTitle: string;
  enableRightEmployeePanel: boolean;
  enableRightEmployeePanelText: string;
  enableRightArchivePanel: boolean;
  enableRightArchivePanelText: string;
  layerOptionWidth: number;
  rightActionPanelWidth: number;
  planFile: string;
  planTypeText: string;
  planSubTypeText: string;
  setforeignObjectInRedlineText: boolean;
  hambugerMenuTooltip: string;
  rightActionPanelTooltip: string;
  leaseStartDate: string;
  leaseEndDate: string;
  defaultLeftPanelOpen: boolean;
  dateRegex: string[];
  actionPanelSide: string;
  maxUploadSize: string;
  topBarLogo: string;
  cadViewerBrandLogoPosition: string;
  cadViewerBrandLogoSize: string;
  showCompareTool: boolean;
  enablePolygonControlPoints: boolean;
  enableHelperMethods: boolean;
  enableHelpersMethodsGroup_Highlight: boolean;
  enableHelpersMethodsGroup_Group: boolean;
  enableHelpersMethodsGroup_Manipulate: boolean;
  enableHelpersMethodsGroup_Insert: boolean;
  enableHelpersMethodsGroup_CustomCanvas: boolean;
  enableHelpersMethodsGroup_SpaceArea: boolean;
  enableHelpersMethodsGroup_RedlineArea: boolean;
  enableHelpersMethodsGroup_VizQueryDemo: boolean;
  helperMethodsActionSize: string;
  topPaneScrollDownTitle: string;
  displayTopPaneScrollDownButton: boolean;
  topRowItem1: string;
  topRowItem2: string;
  topRowItem3: string;
  customOnLoadEndContent: boolean;
  popupCustomMenu1: string;
  popupCustomFontAwesomeIcon1: string;
  popupCustomMenu2: string;
  popupCustomFontAwesomeIcon2: string;
  style_popup: boolean;
  cvjs_styleQTip_color_flag: boolean;
  cvjs_styleQTip_color_v1: string;
  cvjs_styleQTip_color_v2: string;
  cvjs_styleQTip_color_v3: string;
  cvjs_styleQTip_color_v4: string;
  cvjs_styleQTip_color_v5: string;
  cvjs_styleQTip_fontsize_flag: boolean;
  cvjs_styleQTip_fontsize_v1: string;
  cvjs_styleQTip_fontsize_v2: string;
  cvjs_styleQTip_fontsize_v3: string;
  cvjs_styleQTip_fontsize_v4: string;
  cvjs_styleQTip_fontsize_v5: string;
  cvjs_styleQTip_fontsize_v6: string;
  cvjs_styleQTip_processbody_flag: boolean;
  cvjs_styleQTip_width: string;
  settingsGoHomepageButtonText: string;
  enableSpaceObjectsExtraction: boolean;
  showTourInformationDialog: boolean;
  enableHelpButton1: boolean;
  helpbutton1: string;
  helpbutton1link: string;
  enableHelpButton2: boolean;
  helpbutton2: string;
  helpbutton2link: string;
  customHtmlHeaderContent: string;
  enableGeoLocation: boolean;
  geolocationAPIKey: string;
  recaptchaSiteKey: string;
  enableBasicAuth: boolean;
  basicAuthUsername: string;
  basicAuthPassword: string;

  disableAllFeaturesIfNotLoggedIn: boolean;
  defautlPropertyToLoad: {
    propertyNumber: string | undefined;
    planName: string | undefined;
  };
  showLogoOnSideBarLeftPanel: boolean;
  cadViewerBrandLogoOpacity: number; // 0 to 100
  serverSubFolder: string | undefined;
  showOnlySubFolder?: boolean; // if true, only show the serverSubFolder and its children, hide the rest of the tree
  propertySVGFilesLocation: string;
}
