// Keys grouping for accordion sections
export const accordionGroups = {
  "Tenant Overview": [
    "Property #",
    "Tenant Name",
    "DBA",
    "Space Number",
    "GLA",
    "Lease Status",
    "Lease Start Date",
    "Lease End Date",
    "Total Rent",
    "Rent PSF",
    "Sales R12",
    "Kickout Clause Active",
  ],
  "Tenant & Space Info": [
    "Mall Name",
    "DBA",
    "Space #",
    "GLA",
    "Actual Footprint SF",
    "Actual Footprint M2",
    "Merchandise Category",
  ],
  "Lease Financials": [
    "BMR",
    "BMR PSF",
    "Total Rent",
    "Total Rent PSF",
    "Total Rent /M2",
    "Occupancy Cost",
    "Occupancy Cost PSF",
    "Occupancy Cost /M2",
  ],
  "Sales Performance": ["Sales R12", "Sales R12 PSF"],
  "Lease Terms": [
    "Lease ID",
    "Lease Type",
    "Lease Status",
    "Deal Type",
    "Deal ID",
    "Deal Stage",
    "Deal Record Type",
  ],
  "Important Dates": [
    "Lease Start Date",
    "Lease End Date",
    "Rent Expiration Date",
    "Executed Date",
    "ABF RCD",
    "Date of Possession (Mutually Agreed)",
    "Date of Possession (Projected Per TC)",
    "Store Opening (Projected Per TC)",
    "Date of Possession (Actual)",
    "Store Opening (Actual) Date",
  ],
  "Legal Triggers & Flags": ["Kickout Y/N"],
  "Deal Data": [
    "SF of the Deal",
    "Projected R12 Sales",
    "Projected R12 Sales PSF",
    "Deal Name",
    "Projected Rent Commencement Date",
    "Term (Months)",
    "Deal Rent Type",
  ],
  Overview: [
    "Room #",
    "Square Footage",
    "Employee",
    "Email",
    "Phone",
    "Title",
    "Employee Type Code",
    "Department",
  ],
  Others: [], // Will be populated with the rest of the keys
};
